-- Migration 0008: Hiring master tables — companies and interview templates

CREATE TABLE hiring_companies (
  id CHAR(26) NOT NULL PRIMARY KEY,
  lc_no VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  branch VARCHAR(80) NULL,
  location TEXT NULL,
  city VARCHAR(80) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE interview_templates (
  id CHAR(26) NOT NULL PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description TEXT NULL,
  image_url VARCHAR(500) NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
