-- Migration 0009: master tables for divisions, designations, locations and skills

CREATE TABLE divisions (
  id CHAR(26) NOT NULL PRIMARY KEY,
  code VARCHAR(20) NULL UNIQUE,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE designations (
  id CHAR(26) NOT NULL PRIMARY KEY,
  code VARCHAR(20) NULL UNIQUE,
  name VARCHAR(120) NOT NULL UNIQUE,
  department_id CHAR(26) NULL,
  division_id CHAR(26) NULL,
  parent_designation_id CHAR(26) NULL,
  hierarchy_level INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_designations_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
  CONSTRAINT fk_designations_division FOREIGN KEY (division_id) REFERENCES divisions(id) ON DELETE SET NULL,
  CONSTRAINT fk_designations_parent FOREIGN KEY (parent_designation_id) REFERENCES designations(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE locations (
  id CHAR(26) NOT NULL PRIMARY KEY,
  code VARCHAR(20) NULL UNIQUE,
  name VARCHAR(120) NOT NULL UNIQUE,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  branch_id CHAR(26) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_locations_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE skills (
  id CHAR(26) NOT NULL PRIMARY KEY,
  code VARCHAR(20) NULL UNIQUE,
  name VARCHAR(120) NOT NULL UNIQUE,
  category VARCHAR(80) NULL,
  description TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
